sudo: false

language: python
python:
  - "2.7"

services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker pull dwlepage70/smc:v6.1.0
- docker network create --subnet=172.32.0.0/24 mynet
- docker run -d -p 8902-8918:8902-8918 -p 8082:8082 --network=mynet --ip=172.32.0.10 --name smc_container dwlepage70/smc:v6.1.0
- docker exec smc_container /bin/bash -c "/etc/init.d/sgMgtServer start"
- docker exec smc_container /bin/bash -c "/etc/init.d/sgLogServer start"
- pip install coverage
- pip install coveralls

script:
- nosetests --exe --with-coverage --cover-package=smc --cover-erase

after_success:
  coveralls debug
