sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker pull dwlepage70/smc:v6.1.2
- docker network create --subnet=172.32.0.0/24 mynet
- docker run -d -p 8902-8918:8902-8918 -p 8082:8082 --network=mynet --ip=172.32.0.10 --name smc_container dwlepage70/smc:v6.1.2
- docker exec smc_container /bin/bash -c "/etc/init.d/sgMgtServer start"
- docker exec smc_container /bin/bash -c "/etc/init.d/sgLogServer start"
- pip install coverage
- pip install coveralls
- pip install requests-mock

script:
- nosetests --exe --with-coverage --cover-package=smc --cover-html -v

after_success:
  - if [[ $ENV == python=2.7* ]]; then
          coveralls debug;
    fi
